### ISSUE TITLE
Issue: Exception Thrown on Showing The Title

### ISSUE THREAD

**Issue by radekaadek** [PlohnenSoftware/familiada_ZSP#45]
The game throws an exception and bugs out upon starting and then showing the title screen.

Error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 1401, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 172, in fill
    self.refresh()
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 127, in refresh
    pygame.display.update()
pygame.error: Could not make GL context current: BadAccess (attempt to access private resource denied)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 1401, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 218, in <lambda>
    Delay(3, lambda: self.five(0,5)).start()
                     ^^^^^^^^^^^^^^
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 190, in five
    self.write_hor("AAAAA", start_row, start_col)
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 159, in write_hor
    self.refresh()
  File "/home/ard/prg/familiada_ZSP/src/blackboard.py", line 127, in refresh
    pygame.display.update()
pygame.error: Could not make GL context current: BadAccess (attempt to access private resource denied)
```

Steps to reproduce:
1. Press ZACZNIJ
2. Press Napis
3. Wait a few seconds

Error screen:
![image](https://github.com/user-attachments/assets/0495b59c-740f-46ac-b7fa-cf0fe9395d2a)

**Comment by radekaadek** [comment]
Fixed in inDev
